#!/bin/bash
# currently using:
echo "numix icon themes"
sudo add-apt-repository -y ppa:numix/ppa
echo "ultraflat icons"
sudo add-apt-repository -y ppa:noobslab/icons
echo "onionshare"
sudo add-apt-repository -y ppa:micahflee/ppa
echo "neovim"
sudo add-apt-repository -y ppa:neovim-ppa/stable
echo "several themes, including paper icon theme"
sudo add-apt-repository -y ppa:snwh/pulp
echo "offline documentation tool"
sudo add-apt-repository -y ppa:zeal-developers/ppa
echo "chrome gnome shell integration connector"
sudo add-apt-repository -y ppa:ne0sight/chrome-gnome-shell
echo "Stellarium"
sudo add-apt-repository -y ppa:stellarium/stellarium-releases
echo "Razer drivers"
sudo add-apt-repository -y ppa:openrazer/stable
echo "syncthing"
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
