#!/bin/bash
# currently using:
echo "firefox nightly"
sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/ppa
echo "gnome3 and gnome-shell themes"
sudo add-apt-repository -y ppa:webupd8team/themes
echo "elegance and numix gtk themes"
sudo add-apt-repository -y ppa:satyajit-happy/themes
echo "numix icon themes"
sudo add-apt-repository -y ppa:numix/ppa
echo "newer gnome3"
sudo add-apt-repository -y ppa:gnome3-team/gnome3
echo "audio recorder"
sudo add-apt-repository -y ppa:osmoma/audio-recorder
echo "official bitcoin client"
sudo add-apt-repository -y ppa:bitcoin/bitcoin
echo "ultraflat icons"
sudo add-apt-repository -y ppa:noobslab/icons
echo "evolvere icons"
sudo add-apt-repository -y ppa:noobslab/evolvere

# not using because problems in my current version, but want to use:
# echo "faenza icons and faience themes" 
# sudo add-apt-repository -y ppa:tiheum/equinox
# echo "nitrux themes"
# sudo add-apt-repository -y ppa:upubuntu-com/nitrux
