#!/bin/bash
set -e

# download chrome from google web site
rm -f google-chrome-stable_current_amd64.deb
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# update repos and install missing dependencies
sudo apt update
sudo apt install -f -y
