#!/bin/bash
# install hangouts plugin
rm -f google-talkplugin_current_amd64.deb
wget https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
sudo dpkg -i google-talkplugin_current_amd64.deb

# download chrome from google web site
rm -f google-chrome-stable_current_amd64.deb
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

# download keybase from its web site
rm -f keybase_amd64.deb
curl -O https://prerelease.keybase.io/keybase_amd64.deb
sudo dpkg -i keybase_amd64.deb
run_keybase

# update repos and install missing dependencies
sudo apt update
sudo apt install -f -y

# install docker top
sudo wget https://github.com/bcicen/ctop/releases/download/v0.6.0/ctop-0.6.0-linux-amd64 -O /usr/local/bin/ctop
sudo chmod +x /usr/local/bin/ctop 
