#!/bin/bash
sudo apt install -y \
    git \
    git-core \
    git-doc \
    gitg \
    tig \
    tk \
    fish \
    screen \
    openssh-server \
    vim \
    vim-gnome \
    neovim \
    exuberant-ctags \
    gparted \
    gdmap \
    htop \
    iotop \
    ubuntu-restricted-extras \
    weechat \
    meld \
    ppa-purge \
    tmux \
    nethogs \
    p7zip \
    build-essential \
    imagemagick \
    tree \
    python3-pip \
    python3-dev \
    python3-venv \
    run-one \
    nocache \
    expect-dev `# tool to automate other cli tools (inputs, etc)` \
    curl \
    libnet-dbus-perl `# required by the system monitor gnome-shell extension` \
    gnome-session \
    gnome-tweak-tool \
    cmatrix \
    tdfsb `# doom-like process manager` \
    pgtop \
    nfs-common \
    cmus \
    fdupes \
    nginx \
    graphviz \
    arc-theme \
    aria2 `# cli tool for faster downloads, even on normal http links` \
    ttyrec \
    gnupg \
    xbindkeys \
    xautomation \
    pastebinit \
    xclip \
    jq \
    mesa-utils `# advanced audio controls` \
    chrome-gnome-shell \
    rename

# temporary workaround because ack-grep is no longer in ubuntu's repos:
sudo apt install -y cpanminus
sudo cpanm install App::Ack
