#!/bin/bash
set -e

sudo apt install -y \
    git \
    git-core \
    git-doc \
    gitg \
    tig \
    tk \
    fish \
    screen \
    openssh-server \
    vim \
    neovim \
    exuberant-ctags \
    gparted \
    gdmap \
    htop \
    iotop \
    ubuntu-restricted-extras \
    meld \
    ppa-purge \
    tmux \
    nethogs \
    p7zip \
    build-essential \
    imagemagick \
    tree \
    python3-pip \
    python3-dev \
    python3-venv \
    run-one \
    nocache \
    expect-dev `# tool to automate other cli tools (inputs, etc)` \
    curl \
    libnet-dbus-perl `# required by the system monitor gnome-shell extension` \
    gnome-session \
    gnome-tweak-tool \
    cmatrix \
    pgtop \
    nfs-common \
    fdupes \
    nginx \
    graphviz \
    arc-theme \
    gnupg \
    xbindkeys \
    xautomation \
    pastebinit \
    xclip \
    jq \
    mesa-utils `# advanced audio controls` \
    chrome-gnome-shell \
    pass \
    sshfs `# to mounth file systems through ssh` \
    flatpak \
    ulauncher `# nifty little launcher app` \
    units `# unit converter, also used by the units ulauncher plugin` \
    rofi `# dependency of the ulauncher emoji plugin` \
    xdotool `# dependency of the ulauncher emoji plugin` \
    fd-find `# nicer alternative to find` \
    ack-grep `# nicer alternative to grep, for code` \
    pulseeffects `# equalizer and stuff` \
    ecryptfs-utils \
    alacritty `# nice terminal emulator` \
    rclone rclone-browser `# syncer for google drive and other services` \
    solaar `# tool to pair and manage logitech unifying devices` \ 
    diff-so-fancy `# tool for nicer diffs in git, used in .gitconfig` \
    barrier `# app to share mouse, keyboard and clipboard and merge screens between computers` \
    rename


# far better ls
sudo apt install /home/fisa/apps/installers/lsd_0.20.1_amd64.deb


# No longer present, but want:
# v4l2ucp `# powerful webcam control panel` \
