#!/bin/bash
set -e

sudo apt install -y \
    git \
    git-core \
    git-doc \
    gitg \
    tig \
    tk \
    fish \
    screen \
    openssh-server \
    vim \
    neovim \
    exuberant-ctags \
    gparted \
    gdmap \
    htop \
    iotop \
    ubuntu-restricted-extras \
    meld \
    ppa-purge \
    tmux \
    nethogs \
    p7zip \
    build-essential \
    imagemagick \
    tree \
    python3-pip \
    python3-dev \
    python3-venv \
    run-one \
    nocache \
    expect-dev `# tool to automate other cli tools (inputs, etc)` \
    curl \
    libnet-dbus-perl `# required by the system monitor gnome-shell extension` \
    gnome-session \
    gnome-tweak-tool \
    cmatrix \
    tdfsb `# doom-like process manager` \
    pgtop \
    nfs-common \
    cmus \
    fdupes \
    nginx \
    graphviz \
    arc-theme \
    aria2 `# cli tool for faster downloads, even on normal http links` \
    ttyrec \
    ttygif \
    gnupg \
    xbindkeys \
    xautomation \
    pastebinit \
    xclip \
    jq \
    mesa-utils `# advanced audio controls` \
    chrome-gnome-shell \
    pass \
    rofi `# dependency for the emoji chooser` \
    xdotool `# dependency for the emoji chooser` \
    sshfs `# to mounth file systems through ssh` \
    ffmpeg `# video converter and more` \
    flatpak \
    gnome-software-plugin-flatpak `# to be able to install flatpak apps from the store with clicks` \
    ulauncher `# powerful app launcher and more` \
    units `# unit converted, used by an extension of ulauncher` \
    fd-find `# nicer alternative to find` \
    ack-grep `# nicer alternative to grep, for code` \
    postgresql-11 \
    postgresql-server-dev-11 \
    pulseeffects `# equalizer and stuff` \
    alacritty `# nice terminal emulator` \
    rename

# No longer present, but want:
# v4l2ucp `# powerful webcam control panel` \
