#!/bin/bash
set -e

# system tools
python3 -m pip install --user \
    ngxtop \
    pinggraph \
    glances \
    ffind \
    percol `# cli interactive filter for output of programs` \
    speedtest-cli \
    youtube-dl \
    httpie \
    pgcli \
    pythonpy \
    eg \
    magic-wormhole \
    lice `# generate licence files for oss projects` \
    vanity `# pipy downloads stats for packages` \
    ohmu `# disk usage details from a folder, similar to gdmap` \
    sh `# argos scripts dependency` \
    psutil `# argos scripts dependency` \
    neovim `# fisa nvim config dependency` \
    pep8 `# fisa nvim config dependency` \
    flake8 `# fisa nvim config dependency` \
    pyflakes `# fisa nvim config dependency` \
    pylint `# fisa nvim config dependency` \
    isort `# fisa nvim config dependency` \
    fades
