#!/bin/bash

# system tools
pip install \
    httpie \
    supervisor \
    sphinx \
    lice \
    pydot \
    ffind \
    vanity \
    pyparsing==1.5.7 \
    ngxtop \
    percol \
    speedtest-cli \
    pgcli \
    eg \
    whatever \
    pythonpy \
    glances \
    ohmu \
    pinggraph \
    magic-wormhole

pip3 install \
    fades


# fisa neovim config dependencies
pip install neovim pep8 flake8 pyflakes pylint isort
pip3 install neovim pep8 flake8 pyflakes pylint isort

# argos scripts dependencies
pip3 install sh psutil
