#!/bin/bash
set -e

# my crons
crontab /home/fisa/devel/mios/dotfiles/crontab

# my crons that have to be runned as super user
sudo crontab /home/fisa/devel/mios/dotfiles/crontab_su

# my hosts
cat /home/fisa/devel/mios/dotfiles/hosts | sudo tee -a /etc/hosts

# create user invitado
echo " >>>> INVITADO USER"
sudo adduser invitado

# scripts to allow invitado user to share tmux on read-only mode
sudo cp /home/fisa/devel/mios/scripts/read_only_shared_tmux_attach /home/invitado/conectar
sudo chown invitado:invitado /home/invitado/conectar

# add my ssh key
echo " >>>> SSH KEY"
ssh-add /home/fisa/.ssh/fisa_ssh_3

# add local bin path to fish
fish -c "set -U fish_user_paths /home/fisa/.local/bin $fish_user_paths"

# fish configs
mkdir -p /home/fisa/.config/fish/functions
ln -s /home/fisa/devel/mios/dotfiles/config.fish /home/fisa/.config/fish/
ln -s /home/fisa/devel/mios/dotfiles/fish_prompt.fish /home/fisa/.config/fish/functions/
ln -s /home/fisa/devel/mios/dotfiles/fish_right_prompt.fish /home/fisa/.config/fish/functions/

# neovim config installation
echo ">>>> NEOVIM CONFIGS"
mkdir -p /home/fisa/.config/nvim
ln -s /home/fisa/devel/fisa-vim-config/config.vim /home/fisa/.config/nvim/init.vim

# other versioned configs
ln -s /home/fisa/devel/mios/dotfiles/.alacritty.yml /home/fisa/
ln -s /home/fisa/devel/mios/dotfiles/.gitconfig /home/fisa/
ln -s /home/fisa/devel/mios/dotfiles/.ssh/config /home/fisa/.ssh/
ln -s /home/fisa/devel/fisa-tmux-config/.tmux.conf /home/fisa/
ln -s /home/fisa/themes/gnome/installed /home/fisa/.themes
ln -s /home/fisa/themes/icons/installed /home/fisa/.icons
ln -s /home/fisa/themes/fonts/installed /home/fisa/.fonts
mkdir -p /home/fisa/.config/ranger
ln -s /home/fisa/devel/mios/dotfiles/ranger_rc.conf /home/fisa/.config/ranger/rc.conf
mkdir -p /home/fisa/.config/kitty/
ln -s /home/fisa/devel/mios/dotfiles/kitty.conf /home/fisa/.config/kitty/kitty.conf

# argos gnome shell extension scripts
ln -s /home/fisa/devel/mios/argos /home/fisa/.config/

# don't notify when new printers are detected
gsettings set org.gnome.settings-daemon.plugins.print-notifications active false

# enable tap-to-click
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# add ability to unmount cyrene/tero sshfs without sudo password
echo "fisa ALL=NOPASSWD: /bin/umount /home/fisa/servers/tero_cyrene/" | sudo tee /etc/sudoers.d/fisa_umount_cyrene_tero
sudo chmod 0440 /etc/sudoers.d/fisa_umount_cyrene_tero

# add ability to join shared tmux without sudo password for invitado
echo "invitado ALL=NOPASSWD: /usr/bin/tmux -2 -S /tmp/shared_tmux attach -r" | sudo tee /etc/sudoers.d/invitado_shared_tmux
sudo chmod 0440 /etc/sudoers.d/invitado_shared_tmux

# replace fish history file with symlink to custom fish history file
mkdir -p /home/fisa/.local/share/fish
rm /home/fisa/.local/share/fish/fish_history
ln -s /home/fisa/.fish_history /home/fisa/.local/share/fish/fish_history

# add fisa user to the dialout group, so I can run scripts using serial ports (like the microbit) without sudo
sudo usermod -a -G dialout fisa

# add symlink for ctop binary
sudo ln -s /home/fisa/apps/ctop /usr/local/bin/ctop

# install argos extension for gnome 3.36 on ubuntu 20.04 (the one in the official website is broken)
ln -s /home/fisa/apps/argos-gnome-3.36/argos@pew.worldwidemann.com/ /home/fisa/.local/share/gnome-shell/extensions/

# docker configs and permissions
sudo groupadd docker
sudo usermod -aG docker fisa
# and configure docker so it uses the home dir for data
sudo cp /home/fisa/devel/mios/dotfiles/etc_docker/daemon.json /etc/docker/daemon.json
sudo chown root:root /etc/docker/daemon.json
