#!/bin/bash
# my crons
crontab /home/fisa/devel/mios/dotfiles/crontab

# my crons that have to be runned as super user
sudo crontab /home/fisa/devel/mios/dotfiles/crontab_su

# my hosts
cat /home/fisa/devel/mios/dotfiles/hosts | sudo tee -a /etc/hosts

# create user invitado
echo " >>>> INVITADO USER"
sudo adduser invitado

# scripts to allow invitado user to share tmux on read-only mode
sudo cp /home/fisa/scripts/read_only_shared_tmux_attac /home/invitado/conectar
sudo chown invitado:invitado /home/invitado/conectar

# create postgres user
echo " >>>> POSTGRES USER"
sudo -u postgres createuser fisa -s -P
# default postgres database for my user
createdb fisa

# add my ssh key
echo " >>>> SSH KEY"
ssh-add /home/fisa/.ssh/fisa_ssh_3

# add local bin path to fish
fish -c "set -U fish_user_paths /home/fisa/.local/bin $fish_user_paths"

# add syncthing service
mkdir -p /home/fisa/.config/systemd/user
cp /home/fisa/devel/syncthing/etc/linux-systemd/user/syncthing.service /home/fisa/.config/systemd/user
systemctl enable syncthing@fisa.service
systemctl start syncthing@fisa.service

# fish configs
mkdir -p /home/fisa/.config/fish/functions
wget https://raw.githubusercontent.com/Duncaen/fish-django-completions/master/__fish_complete_django.fish -O /home/fisa/.config/fish/functions/__fish_complete_django.fish
ln -s /home/fisa/devel/mios/dotfiles/config.fish /home/fisa/.config/fish/
ln -s /home/fisa/devel/mios/dotfiles/fish_prompt.fish /home/fisa/.config/fish/functions/
ln -s /home/fisa/devel/mios/dotfiles/fish_right_prompt.fish /home/fisa/.config/fish/functions/

# neovim config installation
echo ">>>> NEOVIM CONFIGS"
mkdir -p /home/fisa/.config/nvim
ln -s /home/fisa/devel/fisa-nvim-config/init.vim /home/fisa/.config/nvim/

# argos gnome shell extension scripts
ln -s /home/fisa/devel/mios/argos /home/fisa/.config/

# don't notify when new printers are detected
gsettings set org.gnome.settings-daemon.plugins.print-notifications active false

# enable tap-to-click
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

# add ability to join shared tmux without sudo password for invitado
echo "invitado ALL=NOPASSWD: /usr/bin/tmux -2 -S /tmp/shared_tmux attach -r" | sudo tee -a /etc/sudoers.d/invitado_shared_tmux
sudo chmod 0440 /etc/sudoers.d/invitado_shared_tmux

# replace fish history file with symlink to custom fish history file
rm /home/fisa/.local/share/fish/fish_history
ln -s /home/fisa/.fish_history /home/fisa/.local/share/fish/fish_history
