#!/bin/bash
# my crons
crontab /home/fisa/devel/mios/dotfiles/crontab

# my crons that have to be runned as super user
sudo crontab /home/fisa/devel/mios/dotfiles/crontab_su

# my hosts
cat /home/fisa/devel/mios/dotfiles/hosts | sudo tee -a /etc/hosts

# configure vnc server
echo " >>>> VNC PASSWORD"
x11vnc -storepasswd 

# create user invitado
echo " >>>> INVITADO USER"
sudo adduser invitado

# scripts to allow invitado user to share tmux on read-only mode
sudo cp /home/fisa/scripts/read_only_shared_tmux_attac /home/invitado/conectar
sudo chown invitado:invitado /home/invitado/conectar

# create postgres user
echo " >>>> POSTGRES USER"
sudo -u postgres createuser fisa -s -P
# default postgres database for my user
createdb fisa

# add my ssh key
echo " >>>> SSH KEY"
ssh-add /home/fisa/.ssh/fisa_rsa_2

# gtk2 windows buttons to the right 
# TODO working?? seems to break on the current versions of gnome
# gconftool-2 --set /apps/metacity/general/button_layout --type string ":minimize,maximize,close"

# enable apt progress bar
echo 'Dpkg::Progress-Fancy "1";' | sudo tee /etc/apt/apt.conf.d/99progressbar

