#!/bin/bash
set -e

sudo apt install -y \
     mercurial \
     gource \
     vlc \
     cheese \
     pinta \
     kupfer \
     virtualbox \
     sqlitebrowser \
     easytag \
     rst2pdf \
     inkscape \
     gimp \
     gnome-maps \
     zeal \
     kazam \
     vinagre `# vnc client` \
     guvcview `# show webcam as a clean window, and more` \
     openshot \
     stellarium \
     wine-stable \
     nodejs \
     npm
