#!/bin/bash
set -e

sudo apt install ca-certificates
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update

sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


# docker configs and permissions
sudo groupadd docker
sudo usermod -aG docker fisa
# and configure docker so it uses the home dir for data
sudo cp /home/fisa/devel/mios/dotfiles/etc_docker/daemon.json /etc/docker/daemon.json
sudo chown root:root /etc/docker/daemon.json
