#!/bin/bash
set -e

# dependencies
sudo apt install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# add key and repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# update and install docker
sudo apt update
sudo apt install docker-ce -y

# set permissions
sudo groupadd docker
sudo usermod -aG docker fisa

# and configure docker so it uses the home dir for data
sudo cp /home/fisa/devel/mios/dotfiles/etc_docker/daemon.json /etc/docker/daemon.json
sudo chown root:root /etc/docker/daemon.json
