#!/bin/bash
# this installs bumblebee, a non-official driver for nvidia optimus
# this works for my msi ge60 in ubuntu 15.10
sudo apt-get install bumblebee bumblebee-nvidia primus nvidia-352

echo "DONT FORGET to update your /etc/bumblebee/bumblebee.conf:"
echo "On [bumblebeed], Driver=nvidia"
echo "On [driver-nvidia], KernelDriver=nvidia-352, and the paths pointing to nvidia-352"
echo "Also, you should disable the gpu-manager, which can cause blank screens on boot."
echo "Edit /etc/init/gpu-manager.conf and comment the lines that look like this:"
echo "#start on (starting lightdm or ....)"
