#!/bin/env python3
import sys
from datetime import datetime
from pathlib import Path

# this script is meant to be used from a new "fresh" home dir in the new 
# machine, while having a clone of the old home in an "old_home" dir

# folders and files that I want to carry
to_keep = set("""
    .bash_history
    .gnupg
    .lesshst
    .micropython.history
    .node_repl_history
    .octave_hist
    .password-store
    .pgcli-history
    .python_history
    .selected_editor
    .ssh
    .fonts
    .themes
    .icons
    .gitconfig
    .psqlrc
    .tmux.conf
    .xbindkeysrc
    .alacritty.yml
    .arduinoIDE
    .tigrc
""".split())

new_home_path = Path(".").absolute()
old_home_path = new_home_path / "old_home"
backup_path = new_home_path / f"bkp_dotfiles_{datetime.now().strftime('%Y%m%d')}"

print("Working over", new_home_path, "as the new home and", old_home_path,
      "as the old home from which to port things, is that ok? (y/n)")
if input() != "y":
    print("aborted")
    sys.exit()

print("Unwanted dotfiles will be moved to", backup_path)
if not backup_path.exists():
    backup_path.mkdir()

backed_up = []
ported = []

for old_path in old_home_path.iterdir():
    if old_path.name.startswith("."):
        # a dotfile! decide what to do
        name = old_path.name

        if name in to_keep:
            new_path = new_home_path / name
            if not new_path.exists():
                old_path.rename(new_path)
                to_keep.remove(name)
                ported.append(name)
        else:
            new_path = backup_path / name
            old_path.rename(new_path)
            backed_up.append(name)

print()
if ported:
    print("These were ported to the new home:")
    print(*ported, sep=", ")
else:
    print("WARNING!! No dot files/dirs were ported to the new home!!!")

if to_keep:
    print()
    print("WARNING!! These were listed as things to keep, but weren't found in the old home:")
    print(*to_keep, sep=", ")

print()
if backed_up:
    print("These were backed up, REVIEW if you don't need to port them!!!")
    print(*backed_up, sep=", ")
else:
    print("WARNING!! No unknown files were backed up! That's really weird")
